{% set name = "gopls" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/golang/tools/archive/{{ name }}/v{{ version }}.tar.gz
  sha256: 0805bb9d3bfa51334b4d45a3182daea3e77ecbe27f4ddc672841ec72f63ed20a

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/golang/tools/tree/master/gopls
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for the Go language
  dev_url: https://github.com/golang/tools/tree/master/gopls

extra:
  recipe-maintainers:
    - danielnachun
