{% set name = "gopls" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/golang/tools/archive/{{ name }}/v{{ version }}.tar.gz
  sha256: 1ff2a83be8be5a61b97fc5d72eab66f368ec20b52c513cc6656fc2e502e46f19

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/golang/tools/tree/master/gopls
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for the Go language
  dev_url: https://github.com/golang/tools/tree/master/gopls

extra:
  recipe-maintainers:
    - danielnachun
